//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

// 优惠券
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[sea_orm(table_name = "coupons")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub code: String,
    pub status: i16,
    pub scope_type: i16,
    pub discount_type: i16,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub scope_info: Option<Json>,
    #[sea_orm(column_type = "JsonBinary")]
    pub discount_info: Json,
    #[schema(value_type = String)]
    pub expires_at: Option<DateTimeWithTimeZone>,
    #[schema(value_type = String)]
    pub created_at: DateTimeWithTimeZone,
    #[schema(value_type = String)]
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
