//! `SeaORM` Entity. Generated by sea-orm-codegen

pub mod prelude;
pub mod roles;
pub mod users;
pub mod apps;
pub mod products;
pub mod pay_methods;
pub mod orders;
pub mod coupons;
pub mod coupons_apps;
pub mod coupons_products;
pub mod order_products;
pub mod order_coupons;
pub mod reg_codes;
pub mod order_reg_codes;
pub mod invite_records;
