//! `SeaORM` Entity. Generated by sea-orm-codegen

pub use super::roles::Entity as Roles;
pub use super::users::Entity as Users;
pub use super::apps::Entity as Apps;
pub use super::products::Entity as Products;
pub use super::pay_methods::Entity as PayMethods;
pub use super::orders::Entity as Orders;
pub use super::coupons::Entity as Coupons;
pub use super::coupons_apps::Entity as CouponsApps;
pub use super::coupons_products::Entity as CouponsProducts;
pub use super::order_products::Entity as OrderProducts;
pub use super::order_coupons::Entity as OrderCoupons;
pub use super::reg_codes::Entity as RegCodes;
pub use super::order_reg_codes::Entity as OrderRegCodes;
pub use super::invite_records::Entity as InviteRecords;
