//! `SeaORM` Entity. Generated by sea-orm-codegen

pub use super::coupons::Entity as Coupon;
pub use super::orders::Entity as Order;
pub use super::product_categories::Entity as ProductCategory;
pub use super::products::Entity as Product;
pub use super::reg_codes::Entity as RegCode;
pub use super::roles::Entity as Role;
pub use super::user::Entity as User;
