//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel,Serialize,ToSchema)]
#[sea_orm(table_name = "reg_codes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub code: String,
    pub app_id: i32,
    pub valid_days: i32,
    pub max_devices: i32,
    pub status: i16,
    pub binding_time: Option<DateTime<Utc>>,
    pub code_type: i16,
    pub expire_time: Option<DateTime<Utc>>,
    pub total_count: Option<i32>,
    pub use_count: i32,
    pub device_id: Option<i32>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::apps::Entity",
        from = "Column::AppId",
        to = "super::apps::Column::Id"
    )]
    Apps,
    #[sea_orm(has_many = "super::order_reg_codes::Entity")]
    OrderRegCodes,
    #[sea_orm(
        belongs_to = "super::app_devices::Entity",
        from = "Column::DeviceId",
        to = "super::app_devices::Column::Id"
    )]
    AppDevices,
}

impl Related<super::apps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Apps.def()
    }
}

impl Related<super::order_reg_codes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderRegCodes.def()
    }
}

impl Related<super::app_devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppDevices.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
